"""API routes package."""

from plex_playlist_sync.api.routes import (
    acquisition,
    activity,
    admin_users,
    auth,
    discovery,
    download_clients,
    import_lists,
    indexers,
    issues,
    library,
    missing,
    mixes,
    notifications,
    plex_playlists,
    playlists,
    quality_catalog,
    quality_profiles,
    queue,
    requests,
    scrobbles,
    settings,
    sync,
    system,
    users,
    wanted,
)

__all__ = [
    "acquisition",
    "activity",
    "admin_users",
    "auth",
    "discovery",
    "download_clients",
    "import_lists",
    "indexers",
    "issues",
    "library",
    "missing",
    "mixes",
    "notifications",
    "plex_playlists",
    "playlists",
    "quality_catalog",
    "quality_profiles",
    "queue",
    "requests",
    "scrobbles",
    "settings",
    "sync",
    "system",
    "users",
    "wanted",
]

